### ISSUE TITLE
Reproduce the results in paper

### ISSUE THREAD

**Issue by haithanhp** [titu1994/neural-architecture-search#1]
Hi @titu1994,

Thanks for your great work. I want to reproduce the results of algorithm in Pytorch. I have some concerns with your implementation before seeing the detail in your code:
1. How about the accuracy in Cifar 10, Cifar -100 ?
2. I want to implement transferable learning to deploy model in mobile devices. Could you try to reimplement that before?

Thanks,
Hai

**Comment by titu1994** [comment]
As I've mentioned in the readme, this repository and the PNAS repository are not faithful implementations of the respective papers. I have taken many parameters from personal choice. I sincerely doubt you could match the paper with the repository as it is. 

Also, transferrable learning models are not specialized models designed using this method. You design a general cell and stack more of them to create a large model and fewer of them when you want to create Mobile model.
