### ISSUE TITLE
the accuracy is bad, I mean it is useless

### ISSUE THREAD

**Issue by nk0307** [titu1994/neural-architecture-search#14]

**Comment by titu1994** [comment]
If you mean the example model shown in the repository, of course. It is a 2 layer model being applied on CIFAR 10. What did you expect from such a shallow (albeit wide) model ?

If you have any idea to improve it, do share.

**Comment by nk0307** [comment]
got it

**Comment by gndowns** [comment]
@titu1994 can you close this issue then?
