### ISSUE TITLE
Why keeping the default embedding?

### ISSUE THREAD

**Issue by JiahaoYao** [titu1994/neural-architecture-search#15]
Hi, 
    I do not get why the defaulted embedding is needed here? [https://github.com/titu1994/neural-architecture-search/blob/master/controller.py#L289](https://github.com/titu1994/neural-architecture-search/blob/master/controller.py#L289) Could someone tell me why that matters?

**Comment by titu1994** [comment]
Ease of indexing really. Normally the 0th one is used in word embeddings to denote out of vocabulary words. In my case, it simply made indexing 1-based which was convenient for how I was storing them inside their dictionaries.

**Comment by JiahaoYao** [comment]
Thanks, @titu1994 !
