### ISSUE TITLE
Skip Connection Support

### ISSUE THREAD

**Issue by mkocabas** [titu1994/neural-architecture-search#3]
Hi @titu1994! Really appreciate your works! Currently, I'm inspecting NAS code but I'm confused of adding skip connections to the `state_space`. Can you point out some directions? Thank you!

**Comment by titu1994** [comment]
I've been wondering the same thing actually. I have kinda given up on the code cause ENAS by Google is publically available and so much cleaner than this.

It has significant overhead to understand what is going on, but after that it can find powerful architectures in just 1 day. It's my current go to for NAS work.
