### ISSUE TITLE
RNN and LSTM related question

### ISSUE THREAD

**Issue by ganav** [titu1994/neural-architecture-search#5]
Hello Mr
First of all thanks for sharing your great work. 
I am currently working on recurrent neural network specifically CNN-LSTM (end-to-end training).

I would like to use my own CNN-LSTM instead of random initial architecture provided by automl.
Then i want to obtain new CNN-LSTM (newer version of mine) by using your automl source. 
Can i do this using this source? 
Does this automl provide RNN or LSTM?

**Comment by titu1994** [comment]
I have to remind that this is just a test suite. It is mostly a patchwork example so I don't think you should utilize it for important production/research work !

As to how you can do RNN / LSTM, I think it would be best to use [ENAS](https://github.com/melodyguan/enas) which is the official research code of Google's Efficient Neural Architecture Search. I believe there is a model for Penn Tree Bank code there which you can adapt to simple RNN tasks.

However, to create a new CNN-LSTM architecture, it will be a lot more work.
