### ISSUE TITLE
GPU related question.

### ISSUE THREAD

**Issue by ganav** [titu1994/neural-architecture-search#6]
Hello Mr

I am bit curious that in the original paper the author mentioned that they used
800 GPUs (Graphic cards) which is not possible to try for a student like me.
How did you try it? using only 1 GPU and how long did it take with how many images.
Thank you for your time.

**Comment by titu1994** [comment]
This is *not* a reproduction of the paper. It uses w single GPU. It is only an example, please refer to the readme to see all the issues with it. 

I do *not* recommend using it for research reproduction.
